services:
  - type: web
    name: personal-blog
    env: python
    envVars:
      - key: SECRET_KEY
        value: 5vbjzp)__s(j!b*t%rg)-fi$c*ikcxetq6ptjwk3*=&*j)e*vo
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: personal-blog-db
          property: connectionString

databases:
  - name: personal-blog-db
    plan: free
